import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChatWindow, InfoWindow, Sidebar, TopBar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} p-8 h-screen w-screen grid grid-cols-12 grid-rows-layout gap-8 pb-0`}
      >
        <Sidebar />

        <TopBar />
        <InfoWindow />
        <ChatWindow />

        {children}
      </body>
    </html>
  );
}
