components:
  schemas:
    $ref: [ "./schemas/error/_index.yml","./schemas/users/_index.yml" ]

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  requestBodies: { }
openapi: 3.0.3
info:
  title: ''
  version: ''
tags:
  - name: User
    description: Endpoints to manage users
servers:
  - url: http://localhost:5000/api
    description: Development server
paths:

